export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist ein Cybersecurity Audit?", a: "Ein Cybersecurity Audit ist eine systematische Prüfung der gesamten IT-Sicherheitslage eines Unternehmens – technisch und prozessual. Dabei werden Schwachstellen in Web-Apps, Netzwerken, Cloud-Umgebungen und intern erkannt, nach CVSS 3.1 bewertet und mit Maßnahmenempfehlungen versehen." },
  { q: "Was kostet ein Cybersecurity Audit?", a: "Ein automatisierter Schwachstellenscan kostet bei Sodu Secure ab 1.499 €. Ein manueller Cybersecurity Audit wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert – meist zwischen 4.000 und 20.000 €. Umfangreiche Audits (Full-Stack inkl. Compliance-Prüfung) starten ab 8.000 €. Nutzen Sie den Konfigurator für sofortige Preistransparenz." },
  { q: "Wie lange dauert ein Cybersecurity Audit?", a: "Ein fokussierter Cyber Security Audit (z.B. nur Web oder Netzwerk) dauert 2–5 Tage. Vollständige Unternehmens-Audits inkl. Active Directory und Cloud 1–3 Wochen. Der Bericht wird 48 Stunden nach Testabschluss geliefert." },
  { q: "Erfüllt ein Cybersecurity Audit NIS2-Pflichten?", a: "Ja – ein Sodu Secure Cybersecurity Audit erfüllt die NIS2-Anforderungen für regelmäßige technische Sicherheitsprüfungen (Art. 21 Abs. 2 lit. g). Der Bericht ist für die Vorlage bei Behörden und für ISO 27001 Zertifizierungen geeignet." },
  { q: "Was ist der Unterschied zwischen Cybersecurity Audit und Penetrationstest?", a: "Der Begriff Cybersecurity Audit umfasst oft sowohl technisches Pentesting als auch prozessuale und Compliance-Prüfungen. Ein klassischer Penetrationstest fokussiert tiefer auf technische Exploitation. Sodu Secure kombiniert beides – technisches Pentesting + Compliance-Mapping in einem Bericht." },
  { q: "Wer braucht einen Cybersecurity Audit?", a: "Unternehmen ab 50 Mitarbeitern oder Unternehmen in regulierten Sektoren (Energie, Finance, Gesundheit) sind unter NIS2 zur regelmäßigen Prüfung verpflichtet. Aber auch KMUs sollten mindestens jährlich einen Cybersecurity Audit beauftragen." },
];
