export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist ein Cybersecurity Audit?", a: "Ein Cybersecurity Audit ist eine systematische Prüfung der IT-Sicherheitslage eines Unternehmens, technisch und prozessual. Dabei werden Schwachstellen in Web-Apps, Netzwerken, Cloud-Umgebungen und internen Systemen erkannt, nach CVSS 3.1 bewertet und mit konkreten Maßnahmenempfehlungen versehen. Ergebnis ist ein Bericht, der sowohl für die IT als auch für die Geschäftsführung verwertbar ist." },
  { q: "Was kostet ein Cybersecurity Audit?", a: "Der automatisierte Schwachstellenscan als technischer Baustein liegt bei 1.499 €. Ein manueller Cybersecurity Audit wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert, meist zwischen 4.000 und 20.000 €. Den Ausschlag geben Anzahl der Systeme, Prüftiefe und ob Compliance-Mapping gewünscht ist. Letzteres schlägt am stärksten durch, weil jedes Finding einzeln einer Maßnahme des gewählten Rahmenwerks zugeordnet und begründet wird." },
  { q: "Wie lange dauert ein Cybersecurity Audit?", a: "Ein fokussierter Cybersecurity Audit, etwa nur Web oder Netzwerk, dauert 2 bis 5 Tage. Vollständige Unternehmens-Audits inklusive Active Directory und Cloud benötigen 1 bis 3 Wochen. Den Bericht liefern wir innerhalb von 48 Stunden nach Testabschluss; kritische Findings melden wir sofort während der Prüfung, damit Sie nicht auf den Bericht warten müssen." },
  { q: "Wie läuft ein Cybersecurity Audit ab?", a: "In fünf Schritten: kostenloses Scoping-Gespräch, schriftliche Testfreigabe und Zugangsklärung, Aufnahme und manuelle Prüfung der Systeme mit denselben Techniken, die reale Angreifer einsetzen, Bewertung und Priorisierung der Findings nach CVSS, abschließend Bericht und Ergebnisbesprechung mit IT und Geschäftsführung. Während der gesamten Prüfung bleibt ein Ansprechpartner von uns für Ihre IT erreichbar." },
  { q: "Welche Bereiche werden im Cybersecurity Audit geprüft?", a: "Typischerweise die extern erreichbare Angriffsfläche, Web-Anwendungen und APIs, das interne Netzwerk, Active Directory mit Berechtigungs- und Gruppenstruktur, Cloud-Konfiguration in Azure, AWS oder Google Cloud sowie Patchstand und Härtung der Server und Clients. Auf Wunsch kommen Phishing-Simulationen und ein Abgleich gegen ISO 27001 Annex A hinzu." },
  { q: "Was steht im Bericht eines Cybersecurity Audits?", a: "Der Bericht enthält eine Management-Summary ohne Fachjargon, die vollständige Liste der Findings mit CVSS-Bewertung, reproduzierbaren Nachweisschritten und Screenshots sowie priorisierte Behebungsempfehlungen mit Aufwandseinschätzung. Deutsche und englische Fassung sind beide enthalten; damit lässt er sich auch an internationale Konzernmütter, Auditoren oder Kunden weitergeben." },
  { q: "Erfüllt ein Cybersecurity Audit NIS2-Pflichten?", a: "Ja. Ein Cybersecurity Audit deckt die NIS2-Anforderung nach Art. 21 Abs. 2 lit. f ab, die Wirksamkeit der Risikomanagementmaßnahmen regelmäßig zu bewerten. Der Bericht dient als Nachweis gegenüber Aufsichtsbehörden und lässt sich ebenso für ISO 27001 Control A.8.8, DSGVO Art. 32 und DORA-Resilienztests verwenden." },
  { q: "Wer braucht einen Cybersecurity Audit?", a: "Verpflichtet sind Unternehmen in den NIS2-Sektoren, die kumulativ mindestens 50 Beschäftigte und mehr als 10 Mio. € Jahresumsatz erreichen, sowie Finanzunternehmen unter DORA. Unabhängig davon brauchen Unternehmen einen Audit, wenn Kunden, Ausschreibungen oder Cyberversicherungen einen Nachweis verlangen oder eine ISO-27001-Zertifizierung ansteht." },
  { q: "Ist ein Cybersecurity Audit auch für kleine Unternehmen sinnvoll?", a: "Ja. Automatisierte Angriffe suchen nach verwundbaren Systemen, nicht nach Unternehmensgröße. Für kleine Unternehmen genügt oft ein fokussierter Audit der extern erreichbaren Systeme und der zentralen Web-Anwendung. Als Einstieg eignet sich der Schwachstellenscan ab 1.499 €, der die bekannten Lücken und veralteten Komponenten sichtbar macht." },
  { q: "Was ist der Unterschied zwischen Cybersecurity Audit und Penetrationstest?", a: "Der Begriff Cybersecurity Audit umfasst neben technischem Pentesting meist auch prozessuale und Compliance-Prüfungen, etwa den Abgleich gegen ISO 27001 oder NIS2. Ein klassischer Penetrationstest fokussiert tiefer auf die technische Ausnutzung von Schwachstellen. Sodu Secure kombiniert beides und liefert technisches Pentesting und Compliance-Mapping in einem Bericht." },
  { q: "Gibt es nach dem Cybersecurity Audit einen Retest?", a: "Ja. Nachdem Ihr Team die Findings behoben hat, prüfen wir die kritischen Schwachstellen in einem kostenlosen Retest erneut und dokumentieren den bereinigten Stand. Diese Bestätigung ist für Auditoren und Versicherungen oft wichtiger als der Erstbericht, weil sie belegt, dass die Lücken tatsächlich geschlossen wurden." },
];
