export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was bedeutet IT Sicherheit testen?", a: "IT Sicherheit testen bedeutet, die eigene IT-Infrastruktur (Web-Apps, Netzwerke, Cloud, Active Directory) gezielt auf Schwachstellen zu prüfen, bevor Angreifer sie finden. Ein professioneller IT Sicherheitstest wird von zertifizierten Experten von Hand durchgeführt, die gefundene Lücken auch ausnutzen und zu Angriffsketten verbinden, und endet mit einem Bericht, der jedes Finding belegt und priorisiert." },
  { q: "Was kostet es, die IT Sicherheit testen zu lassen?", a: "Der automatisierte Schwachstellenscan liegt bei 1.499 €. Ein manueller IT Sicherheitstest wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert, meist zwischen 4.000 und 20.000 €. Für laufende Überwachung zwischen den Tests gibt es AuditAI ab 99 € pro Monat. Welche Variante passt, entscheidet sich daran, ob ein Nachweis zu einem festen Termin gebraucht wird oder neue Lücken laufend auffallen sollen." },
  { q: "Wie kann ich prüfen, ob mein System sicher ist?", a: "Verlässlich nur, indem jemand den Angriff mit Ihrer Freigabe tatsächlich durchspielt. Dabei wird die von außen erreichbare Angriffsfläche aufgenommen, eingesetzte Software gegen bekannte CVE-Schwachstellen abgeglichen und geprüft, ob sich Authentifizierung umgehen, Berechtigungen ausweiten oder Daten abgreifen lassen. Selbsteinschätzungen, Checklisten und Firewall-Logs ersetzen diesen praktischen Nachweis nicht." },
  { q: "Welche Systeme sollte ich auf IT-Sicherheit testen lassen?", a: "Beginnen Sie mit allem, was aus dem Internet erreichbar ist: Web-Anwendungen, APIs, VPN- und Mail-Gateways, Remote-Zugänge. Danach folgen das interne Netzwerk, Active Directory mit seinem Berechtigungskonzept und die Cloud-Konfiguration. Priorität haben Systeme, die personenbezogene Daten verarbeiten oder deren Ausfall den Geschäftsbetrieb stoppen würde." },
  { q: "Wie lange dauert ein IT Sicherheitstest?", a: "Eine einzelne Web-Anwendung ist in 3 bis 5 Testtagen geprüft, ein Netzwerk in 5 bis 10 Tagen, unternehmensweite Tests mit Active Directory und Cloud benötigen 2 bis 4 Wochen. Den Bericht liefern wir innerhalb von 48 Stunden nach Testabschluss, kritische Findings melden wir sofort während des Tests." },
  { q: "Wie oft sollte ich IT Sicherheit testen lassen?", a: "Mindestens einmal jährlich und nach jeder größeren Systemänderung wie Deployment, Migration oder neuer Infrastruktur. NIS2 und ISO 27001 fordern regelmäßige Sicherheitsprüfungen, DSGVO Art. 32 eine regelmäßige Wirksamkeitsprüfung. Viele Unternehmen testen halbjährlich oder nach jedem größeren Release-Zyklus und überwachen dazwischen laufend per Scan." },
  { q: "Kann ich IT Sicherheit remote testen lassen?", a: "Ja. Alle IT Sicherheitstests können vollständig remote über VPN oder Test-Account durchgeführt werden, das spart Zeit und Reisekosten. Sodu Secure testet von Berlin aus deutschlandweit und international; für interne Netzwerk- oder WLAN-Tests ist ein Vor-Ort-Einsatz möglich." },
  { q: "Was gehört alles zur IT-Sicherheit?", a: "Technik, Organisation und Menschen. Technisch gehören Netzwerk- und Serverhärtung, sichere Software-Entwicklung, Patchmanagement, Verschlüsselung, Zugriffs- und Rechtekonzepte sowie Backup und Notfallwiederherstellung dazu. Organisatorisch kommen Richtlinien, Rollen, Lieferantenprüfung und Incident-Response hinzu, personell Schulungen und Awareness. Ein IT Sicherheitstest prüft, ob diese Maßnahmen technisch tatsächlich wirken." },
  { q: "Kann ich IT Sicherheit auch mit kostenlosen Tools testen?", a: "Kostenlose Scanner wie OpenVAS oder Nmap zeigen offene Ports, Versionsstände und bekannte CVE-Schwachstellen und sind ein sinnvoller erster Schritt. Sie bewerten aber nicht, welche Funde in Ihrem Kontext wirklich gefährlich sind, und finden keine Logikfehler oder Angriffsketten. Für Nachweise gegenüber Auditoren, Kunden und Versicherungen reicht ein Eigenscan nicht aus." },
  { q: "Was sind die häufigsten Schwachstellen beim IT Sicherheitstest?", a: "Regelmäßig finden wir schwache oder fehlende Multi-Faktor-Authentifizierung, veraltete Software mit bekannten CVE-Schwachstellen, unsichere oder ungeschützte API-Endpunkte, fehlerhafte Berechtigungsprüfungen in Web-Anwendungen, Fehlkonfigurationen im Active Directory und überprivilegierte Cloud-Rollen. Viele davon entstehen nicht durch fehlende Technik, sondern durch gewachsene Konfigurationen, die nie überprüft wurden." },
  { q: "Bekomme ich nach dem IT Sicherheitstest Unterstützung bei der Behebung?", a: "Ja. Der Bericht enthält für jedes Finding konkrete Remediation-Empfehlungen mit Aufwandseinschätzung, und wir besprechen die Ergebnisse mit Ihrem Team. Sind die kritischen Lücken geschlossen, testen wir sie ohne Zusatzkosten ein zweites Mal und halten den bereinigten Stand als Nachweis für Auditoren, Kunden und Versicherungen fest." },
  { q: "Was muss vor einem IT Sicherheitstest schriftlich geregelt sein?", a: "Vier Dokumente: eine Vertraulichkeitsvereinbarung, die Testfreigabe des Systemverantwortlichen mit Unterschrift, der abgegrenzte Scope aus Domains, IP-Bereichen und Anwendungen sowie das vereinbarte Zeitfenster mit Notfallkontakt. Liegen Systeme bei einem Hoster oder Cloud-Anbieter, klären wir dessen Testerlaubnis mit ab. Ohne unterschriebene Freigabe beginnt kein Test, weil dieselben Handlungen sonst rechtswidrig wären." },
];
