// Blog data for metadata generation
export const blogPosts = [
  {
    id: 1,
    slug: '1',
    title: 'Understanding SQL Injection: A Deep Dive into Database Security',
    description: 'Learn about SQL injection vulnerabilities, how they work, and comprehensive strategies to protect your database from attacks. Essential reading for developers and security professionals.',
    category: 'Web Security',
    author: 'Dr. Sarah Mitchell',
    date: '2024-12-01',
    readTime: '8 min read',
    image: '/images/blogs/image1.png',
    keywords: ['SQL injection', 'database security', 'web security', 'OWASP', 'SQLi prevention'],
  },
  {
    id: 2,
    slug: '2',
    title: 'Zero-Day Vulnerabilities: Detection and Response Strategies',
    description: 'Explore zero-day vulnerabilities, their impact on cybersecurity, and effective strategies for detection and response in enterprise environments.',
    category: 'Threat Intelligence',
    author: 'Marcus Chen',
    date: '2024-11-28',
    readTime: '10 min read',
    image: '/images/blogs/image2.png',
    keywords: ['zero-day', 'vulnerability detection', 'threat intelligence', 'incident response'],
  },
  {
    id: 3,
    slug: '3',
    title: 'API Security Best Practices for Modern Applications',
    description: 'Comprehensive guide to securing REST and GraphQL APIs. Learn authentication, authorization, rate limiting, and common API vulnerabilities.',
    category: 'API Security',
    author: 'Elena Rodriguez',
    date: '2024-11-25',
    readTime: '12 min read',
    image: '/images/blogs/image3.png',
    keywords: ['API security', 'REST API', 'GraphQL', 'authentication', 'authorization'],
  },
  {
    id: 4,
    slug: '4',
    title: 'Mobile App Security: iOS vs Android Threat Landscape',
    description: 'Compare security challenges in iOS and Android platforms. Learn platform-specific vulnerabilities and security best practices for mobile development.',
    category: 'Mobile Security',
    author: 'James Anderson',
    date: '2024-11-22',
    readTime: '15 min read',
    image: '/images/blogs/image4.png',
    keywords: ['mobile security', 'iOS security', 'Android security', 'mobile pentesting', 'OWASP MASVS'],
  },
  {
    id: 5,
    slug: '5',
    title: 'Cloud Security Fundamentals: AWS, Azure, and GCP',
    description: 'Essential guide to cloud security across major platforms. Learn about IAM, encryption, network security, and compliance in cloud environments.',
    category: 'Cloud Security',
    author: 'Maya Patel',
    date: '2024-11-18',
    readTime: '14 min read',
    image: '/images/blogs/image5.png',
    keywords: ['cloud security', 'AWS security', 'Azure security', 'GCP security', 'cloud compliance'],
  },
  {
    id: 6,
    slug: '6',
    title: 'Social Engineering: The Human Factor in Cybersecurity',
    description: 'Understand social engineering tactics, phishing attacks, and how to build a security-aware culture in your organization.',
    category: 'Security Awareness',
    author: 'Dr. Sarah Mitchell',
    date: '2024-11-15',
    readTime: '9 min read',
    image: '/images/blogs/image6.png',
    keywords: ['social engineering', 'phishing', 'security awareness', 'human factor', 'security training'],
  },
  {
    id: 7,
    slug: '7',
    title: 'React4Shell Vulnerability: Analysis and Mitigation',
    description: 'Deep dive into the React4Shell vulnerability, its impact on React applications, and comprehensive mitigation strategies for developers.',
    category: 'Vulnerabilities',
    author: 'Marcus Chen',
    date: '2025-01-15',
    readTime: '11 min read',
    image: '/images/blogs/image7.png',
    keywords: ['React4Shell', 'React security', 'vulnerability analysis', 'CVE', 'web frameworks'],
  },
  {
    id: 8,
    slug: '8',
    title: 'OpenClaw Framework: Advanced Penetration Testing',
    description: 'Introduction to the OpenClaw penetration testing framework. Learn advanced techniques for security assessments and vulnerability discovery.',
    category: 'Pentesting Tools',
    author: 'Elena Rodriguez',
    date: '2025-01-10',
    readTime: '13 min read',
    image: '/images/blogs/image8.png',
    keywords: ['OpenClaw', 'penetration testing', 'security tools', 'pentesting framework', 'ethical hacking'],
  },
  {
    id: 9,
    slug: '9',
    title: 'SME Penetration Testing: Affordable Security for Small Business',
    description: 'Cost-effective penetration testing strategies for small and medium enterprises. Learn how SMEs can implement professional security testing on a budget.',
    category: 'SME Security',
    author: 'James Anderson',
    date: '2025-01-05',
    readTime: '10 min read',
    image: '/images/blogs/image9.png',
    keywords: ['SME security', 'small business security', 'affordable pentesting', 'budget security'],
  },
  {
    id: 10,
    slug: '10',
    title: 'OWASP Top 10 2026: New Threats and Mitigations',
    description: 'Comprehensive analysis of the OWASP Top 10 2026 update. Discover new threats, changed rankings, and updated mitigation strategies.',
    category: 'OWASP',
    author: 'Dr. Sarah Mitchell',
    date: '2026-01-30',
    readTime: '16 min read',
    image: '/images/blogs/image10.png',
    keywords: ['OWASP Top 10', 'web security', '2026', 'security threats', 'vulnerability trends'],
  },
  {
    id: 11,
    slug: '11',
    title: 'OSCP Certification Path: Complete Guide to Success',
    description: 'Your roadmap to OSCP certification. Study materials, lab exercises, exam tips, and career advancement strategies for aspiring penetration testers.',
    category: 'Certifications',
    author: 'Marcus Chen',
    date: '2024-12-10',
    readTime: '20 min read',
    image: '/images/blogs/image1.png',
    keywords: ['OSCP', 'certification', 'penetration testing', 'ethical hacking', 'career development'],
  },
  {
    id: 12,
    slug: '12',
    title: 'GDPR & Penetration Testing: How Compliance and Security Work Together',
    description: 'Discover how GDPR (DSGVO) and penetration testing align. Learn why security testing supports Article 32, reduces breach risk, and proves data protection in practice.',
    category: 'Compliance & Pentesting',
    author: 'Sodu Secure Team',
    date: '2026-02-11',
    readTime: '12 min read',
    image: '/images/blogs/dsgvo-image-blog-pentest.jpg',
    keywords: ['GDPR', 'DSGVO', 'penetration testing', 'data protection', 'Article 32', 'compliance'],
  },
  {
    id: 13,
    slug: '5-sicherheitsluecken-kmu',
    title: '5 Sicherheitslücken, die wir bei nahezu jedem KMU finden',
    description: 'Cyberangriffe treffen längst nicht mehr nur Konzerne. Welche 5 kritischen Sicherheitslücken wir bei nahezu jedem KMU entdecken – und wie Sie sich schützen können, bevor es teuer wird.',
    category: 'KMU Security',
    author: 'Kerim K.',
    date: '2026-02-26',
    readTime: '10 min read',
    image: '/images/blogs/image9.png',
    keywords: ['Pentest Berlin', 'Pentest KMU', 'IT Security KMU Berlin', 'Cybersecurity KMU Berlin', 'Active Directory Sicherheit', 'Phishing KMU Berlin', 'Ransomware KMU', 'KMU Sicherheitslücken Berlin', 'Penetrationstest Berlin', 'IT-Sicherheit Berlin'],
  },
  {
    id: 14,
    slug: '14',
    title: 'Pentest Berlin: Kostenloser Penetrationstest für Berliner KMUs – Jetzt bewerben',
    description: 'Professioneller Pentest in Berlin – völlig kostenfrei für ausgewählte KMUs. Erfahren Sie, was unser Penetrationstest umfasst, warum Berliner Unternehmen ihn brauchen und wie Sie sich Ihren Platz sichern.',
    category: 'Pentest Berlin',
    author: 'Sodu Secure Team',
    date: '2026-02-27',
    readTime: '8 min read',
    image: '/images/blogs/image9.png',
    keywords: ['Pentest Berlin', 'Penetrationstest Berlin', 'KMU Pentest Berlin', 'Kostenloser Pentest Berlin', 'IT-Sicherheit Berlin', 'Cybersecurity Berlin', 'Pentest Anbieter Berlin', 'Pentest Kosten', 'Pentest KMU'],
  },
  {
    id: 14,
    slug: 'pentest-berlin-leitfaden',
    title: 'Pentest Berlin 2026: Der vollständige Leitfaden für Berliner Unternehmen',
    description: 'Was kostet ein Pentest in Berlin? Was testet man wie? Welche Berliner Unternehmen brauchen einen Penetrationstest – und warum jetzt? Der komplette Guide von SODU Secure.',
    category: 'Pentest Berlin',
    author: 'Kerim K.',
    date: '2026-02-27',
    readTime: '14 min read',
    image: '/images/blogs/image9.png',
    keywords: [
      'Pentest Berlin',
      'Penetrationstest Berlin',
      'Penetration Testing Berlin',
      'Pentest KMU Berlin',
      'IT-Sicherheit Berlin',
      'Pentest Kosten Berlin',
      'Cybersecurity Berlin',
      'Web Application Pentest Berlin',
      'Active Directory Pentest Berlin',
      'Pentest Anbieter Berlin',
      'Ethical Hacking Berlin',
    ],
  },
  {
    id: 15,
    slug: 'pentest-ablauf',
    title: 'Pentest Ablauf: Wie läuft ein Penetrationstest wirklich ab? (2026)',
    description: 'Schritt für Schritt erklärt: Wie läuft ein professioneller Penetrationstest ab? Von der Auftragsklärung über die aktive Testphase bis zum fertigen Report – der vollständige Pentest-Ablauf.',
    category: 'Pentest Ablauf',
    author: 'Kerim K.',
    date: '2026-02-27',
    readTime: '12 min read',
    image: '/images/blogs/image9.png',
    keywords: [
      'Pentest Ablauf',
      'Penetrationstest Ablauf',
      'wie läuft ein Pentest ab',
      'Pentest Phasen',
      'Pentest Schritte',
      'Penetration Testing Ablauf',
      'Pentest Vorbereitung',
      'Pentest Report',
      'Pentest Berlin',
      'Pentest KMU',
    ],
  },
  {
    id: 16,
    slug: 'it-security-check-firma',
    title: 'IT Security Check Firma: Was ist ein IT-Sicherheitscheck für Unternehmen? (2026)',
    description: 'Was ist ein IT Security Check für Unternehmen? Welche Bereiche werden geprüft, was kostet er und wann braucht Ihr Unternehmen einen IT-Sicherheitscheck? Der vollständige Praxisleitfaden für Firmen jeder Größe.',
    category: 'IT Security Check',
    author: 'Kerim K.',
    date: '2026-02-27',
    readTime: '13 min read',
    image: '/images/blogs/image9.png',
    keywords: [
      'IT Security Check Firma',
      'IT Sicherheitscheck Unternehmen',
      'IT Security Check',
      'IT Sicherheitscheck',
      'Sicherheitscheck IT',
      'IT Security Check Berlin',
      'Unternehmens IT Security Check',
      'IT Sicherheitsprüfung',
      'IT Sicherheit KMU',
      'Cybersecurity Check Unternehmen',
      'IT Security Überprüfung',
      'IS Sicherheitsaudit',
    ],
  },
  {
    id: 17,
    slug: 'it-security-audit',
    title: 'IT Security Audit & IS Sicherheitsaudit: Der vollständige Leitfaden für Unternehmen (2026)',
    description: 'Was ist ein IT Security Audit? Was unterscheidet ein IT-Sicherheitsaudit vom IS-Sicherheitsaudit? Wie läuft ein Audit ab, was kostet es – und wie bereitet sich Ihr Unternehmen optimal vor? Alles in einem Guide.',
    category: 'IT Security Audit',
    author: 'Kerim K.',
    date: '2026-02-27',
    readTime: '15 min read',
    image: '/images/blogs/image9.png',
    keywords: [
      'IT Security Audit',
      'IS Sicherheitsaudit',
      'IT Sicherheitsaudit',
      'IT Security Audit Unternehmen',
      'Informationssicherheitsaudit',
      'IT Audit',
      'Security Audit Deutschland',
      'IT Security Audit Berlin',
      'IS Security Audit',
      'IT Sicherheits Audit KMU',
      'Cybersecurity Audit',
      'IT Security Check Firma',
      'Sicherheitsaudit ISO 27001',
    ],
  },
];

export function getBlogById(id: number | string) {
  if (typeof id === 'number') {
    return blogPosts.find(blog => blog.id === id);
  }
  const numId = parseInt(id, 10);
  if (!isNaN(numId)) {
    const byId = blogPosts.find(blog => blog.id === numId);
    if (byId) return byId;
  }
  // keyword slug fallback
  return blogPosts.find(blog => blog.slug === id);
}

export function getAllBlogSlugs() {
  return blogPosts.map(blog => blog.slug);
}
