export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist ein IT Sicherheitscheck?", a: "Ein IT Sicherheitscheck (auch IT Security Check) ist eine systematische manuelle Prüfung Ihrer IT-Infrastruktur durch Sicherheitsexperten. Im Gegensatz zu automatisierten Scannern decken zertifizierte Pentester auch komplexe Logikfehler und Angriffsketten auf, bei denen mehrere für sich harmlose Schwächen zu einem kritischen Zugriff kombiniert werden." },
  { q: "Was kostet ein IT Sicherheitscheck?", a: "Für den Einstieg kostet ein automatisierter Schwachstellenscan 1.499 €. Ein manueller IT Sicherheitscheck wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert, meist zwischen 4.000 und 20.000 €, abhängig vom Umfang (Web-App, Netzwerk, Active Directory, Cloud). Am unteren Ende der Spanne bleibt, wer mit einem dieser vier Bereiche beginnt, statt alle gleichzeitig prüfen zu lassen." },
  { q: "Wie läuft ein IT Sicherheitscheck ab?", a: "In fünf Schritten: kostenloses Scoping-Gespräch, schriftliche Testfreigabe und Bereitstellung der Zugänge, manuelle Prüfung der Systeme im vereinbarten Zeitfenster, Bewertung der Findings nach CVSS und abschließend Bericht mit Ergebnisbesprechung. Umfang, Prüftiefe und Zeitfenster halten wir vorher schriftlich fest, damit während des Tests nichts nachverhandelt wird." },
  { q: "Wie schnell erhalte ich die Ergebnisse?", a: "Sodu Secure liefert den vollständigen IT Sicherheitscheck-Bericht innerhalb von 48 Stunden nach Testabschluss. Für kritische Findings kommunizieren wir sofort während des Tests, damit Sie sie nicht erst Tage später erfahren. Die 48-Stunden-Lieferung des Berichts sagen wir im Angebot verbindlich zu." },
  { q: "Was müssen wir für den IT Sicherheitscheck vorbereiten?", a: "In der Regel eine Liste der zu prüfenden Domains, IP-Bereiche und Anwendungen, eine schriftliche Testfreigabe des Systemverantwortlichen sowie Testzugänge für authentifizierte Prüfungen. Für interne Checks kommt ein VPN-Zugang hinzu. Dokumentation ist hilfreich, aber keine Voraussetzung - fehlende Informationen erarbeiten wir uns im Test selbst." },
  { q: "Ist der IT Sicherheitscheck ein Risiko für den laufenden Betrieb?", a: "Nein. Wir testen mit abgestimmter Intensität in einem vereinbarten Zeitfenster und schließen Denial-of-Service-Tests standardmäßig aus. Besonders eingriffsintensive Prüfungen laufen auf Staging-Umgebungen oder außerhalb der Geschäftszeiten. Während des Tests ist ein Ansprechpartner erreichbar, der die Prüfung bei Auffälligkeiten sofort stoppen kann." },
  { q: "Kann ein IT Sicherheitscheck remote durchgeführt werden?", a: "Ja. Der IT Sicherheitscheck wird vollständig remote über VPN oder Test-Account durchgeführt, das spart Zeit und Reisekosten. Für interne Infrastruktur-Checks, WLAN-Prüfungen oder Workshops mit Ihrem Team kann optional auch ein Vor-Ort-Einsatz vereinbart werden; Sodu Secure sitzt in Berlin und testet deutschlandweit." },
  { q: "Welche Compliance-Anforderungen erfüllt ein IT Sicherheitscheck?", a: "Der Bericht liefert Nachweise für NIS2 Art. 21, ISO 27001 Control A.8.8 zum Umgang mit technischen Schwachstellen, DSGVO Art. 32 Abs. 1 lit. d zur regelmäßigen Wirksamkeitsprüfung sowie für DORA-Resilienztests. Einreichen lässt er sich damit bei Behörden, Auditoren und Versicherungen, auf Deutsch wie auf Englisch." },
  { q: "Was sind die vier Säulen der IT-Sicherheit?", a: "Die klassischen Schutzziele sind Vertraulichkeit, Integrität, Verfügbarkeit und Authentizität. Ein IT Sicherheitscheck prüft alle vier praktisch: ob Unbefugte an Daten kommen, ob Daten unbemerkt verändert werden können, ob Systeme durch Fehlkonfiguration ausfallen und ob sich Identitäten fälschen oder Berechtigungen ausweiten lassen." },
  { q: "Reicht ein automatisierter Scanner statt eines IT Sicherheitschecks?", a: "Ein Scanner findet bekannte CVE-Schwachstellen und veraltete Versionen, übersieht aber Logikfehler, fehlende Berechtigungsprüfungen, Angriffsketten und Fehler in der Geschäftslogik - also genau die Lücken, die in echten Angriffen ausgenutzt werden. Sinnvoll ist die Kombination: laufende Scans für die Fläche, ein manueller IT Sicherheitscheck für die Tiefe." },
  { q: "Was ist der Unterschied zwischen IT Sicherheitscheck und Penetrationstest?", a: "Die Begriffe werden oft synonym verwendet. Ein IT Sicherheitscheck ist meist etwas breiter gefasst und umfasst neben technischem Testing auch Prozess- und Konfigurationsprüfungen. Ein Penetrationstest fokussiert tiefer auf die aktive Ausnutzung von Schwachstellen bis zum belegten Zugriff. Sodu Secure kombiniert beides in einem Projekt und einem Bericht." },
];
