export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist eine Hacker Simulation?", a: "Bei einer Hacker Simulation (auch Penetrationstest oder Ethical Hacking) greifen autorisierte Sicherheitsexperten Ihr Unternehmen mit denselben Methoden an wie echte Hacker. Das Ziel: Schwachstellen finden und beheben, bevor echte Angreifer sie ausnutzen." },
  { q: "Ist eine Hacker Simulation legal?", a: "Ja - autorisiertes Ethical Hacking ist vollständig legal. Sodu Secure führt alle Tests ausschließlich mit schriftlicher Genehmigung des Systeminhabers und in klar definiertem Scope durch. Wir stellen alle rechtlichen Dokumente (NDA, ROE, Scope-Agreement) bereit." },
  { q: "Was kostet eine Hacker Simulation?", a: "Der automatisierte Schwachstellenscan beginnt bei 1.499 €. Eine manuelle Hacker Simulation wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert, meist zwischen 4.000 und 20.000 €. Ob eine einzelne Anwendung oder das ganze Unternehmen nachgestellt wird, verschiebt den Aufwand am stärksten, weil im zweiten Fall auch Mitarbeitende und interne Netze Teil des Szenarios sind." },
  { q: "Wie läuft eine Hacker Simulation ab?", a: "Eine Hacker Simulation läuft in fünf Schritten ab: Scoping und schriftliche Freigabe, Informationssammlung über Ihr Unternehmen, Identifikation der Schwachstellen, kontrollierte Ausnutzung mit Nachweis und Ausweitung der Rechte, zuletzt Bericht und Abschlussgespräch. Kritische Funde melden wir sofort während des Tests. Sind die Lücken geschlossen, spielen wir die erfolgreichen Angriffspfade ohne Aufpreis erneut durch und zeigen, an welcher Stelle sie jetzt abbrechen." },
  { q: "Welche Arten von Hacker-Simulationen gibt es?", a: "Unterschieden wird nach Informationsstand: Black Box ohne Vorwissen wie ein externer Angreifer, Grey Box mit Benutzerkonto wie ein Angreifer nach erfolgreichem Phishing, White Box mit vollem Einblick inklusive Quellcode. Dazu kommen die Zielbereiche Webanwendung, externes Netzwerk, internes Netzwerk mit Active Directory, Cloud und Mitarbeiter über Social Engineering." },
  { q: "Wie unterscheidet sich Hacker Simulation von einem Pentest?", a: "Hacker Simulation und Penetrationstest sind weitgehend synonym. Eine Hacker Simulation betont die Realitätsnähe - echte Angriffstechniken, echte Tools (Metasploit, BloodHound, Burp Suite), echte Proof-of-Concepts. Sodu Secure kombiniert klassischen OWASP-basierten Pentest mit simulierten Angriffen." },
  { q: "Was bedeutet Pentester und wer führt die Hacker Simulation durch?", a: "Ein Pentester ist ein Sicherheitsexperte, der mit ausdrücklicher Erlaubnis in Systeme eindringt, um Schwachstellen vor echten Angreifern zu finden. Bei Sodu Secure führen ausschließlich zertifizierte Pentester mit OSCP, OSWE oder CEH die Tests durch - mit über 500 durchgeführten Pentests, ausschließlich mit schriftlicher Beauftragung und in klar abgegrenztem Scope." },
  { q: "Wie lange dauert eine Hacker Simulation?", a: "Eine fokussierte Hacker Simulation (z.B. nur Web-App) dauert 2 bis 3 Tage. Eine vollständige Unternehmens-Simulation (Web + Netzwerk + AD + Phishing) 1 bis 2 Wochen. Der Bericht wird 48 Stunden nach Testende geliefert." },
  { q: "Kann die Hacker Simulation unsere Systeme beschädigen?", a: "Nein, nicht bei sauberem Vorgehen. Wir arbeiten nach vorab abgestimmten Rules of Engagement, verzichten ohne ausdrückliche Freigabe auf Denial-of-Service-Tests und destruktive Aktionen und halten während des Tests einen direkten Draht zu Ihrer IT. Auf Wunsch testen wir in einer Staging-Umgebung oder außerhalb der Geschäftszeiten." },
  { q: "Was passiert wenn die Hacker Simulation kritische Lücken findet?", a: "Bei kritischen Findings kommunizieren wir sofort - noch während des Tests, bevor der Abschlussbericht fertig ist. Sie erhalten Sofortmaßnahmen und können direkt reagieren. Im Bericht steht anschließend, wie die Lücke ausgenutzt wurde und welche Systeme dahinter erreichbar gewesen wären." },
  { q: "Was steht im Bericht nach der Hacker Simulation?", a: "Der Bericht enthält eine Management-Zusammenfassung, jede Schwachstelle mit Risikobewertung, Nachweis der Ausnutzung und Behebungsempfehlung sowie die nachgestellten Angriffspfade - also wie ein Angreifer von außen bis an Ihre Daten gekommen wäre. Den Bericht gibt es in einer deutschen und einer englischen Fassung; beide eignen sich zur Vorlage bei Kunden, Versicherern und Auditoren." },
  { q: "Ist eine Hacker Simulation auch für kleine Unternehmen sinnvoll?", a: "Ja. Kleine Unternehmen sind für Angreifer attraktiv, weil dort seltener geprüft wird und dieselben Standardsysteme laufen wie in Konzernen. Eine fokussierte Hacker Simulation auf die von außen erreichbaren Systeme kostet deutlich weniger als eine Vollprüfung und zeigt die wichtigsten Angriffswege. Der Scope lässt sich auf die Systeme begrenzen, über die ein Angreifer realistisch einsteigen würde." },
];
