export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist ein IT Sicherheitsaudit?", a: "Ein IT Sicherheitsaudit (Sicherheitsaudit) ist eine umfassende Überprüfung der IT-Sicherheitslage eines Unternehmens – technisch und organisatorisch. Dabei werden Schwachstellen identifiziert, gegen Compliance-Anforderungen geprüft und mit priorisierten Maßnahmen versehen." },
  { q: "Was kostet ein Sicherheitsaudit?", a: "Ein automatisierter Schwachstellenscan kostet bei Sodu Secure ab 1.499 €. Ein manueller Sicherheitsaudit wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert – meist zwischen 4.000 und 20.000 €; ein vollständiger Audit inkl. Compliance-Prüfung startet ab 8.000 €. Nutzen Sie den Konfigurator für ein schnelles, unverbindliches Angebot." },
  { q: "Wie lange dauert ein Sicherheitsaudit?", a: "Ein fokussierter IT Sicherheitsaudit dauert 2–5 Tage. Ein vollständiger Unternehmens-Audit (technisch + Compliance + organisatorisch) 1–2 Wochen. Bericht-Lieferung 48 Stunden nach Testabschluss." },
  { q: "Für welche Compliance-Anforderungen brauche ich einen Sicherheitsaudit?", a: "NIS2 (Art. 21 – regelmäßige Risikomanagement-Maßnahmen), ISO 27001 (Annex A.12.6), DSGVO Art. 32 (technische Sicherheitsmaßnahmen) und DORA (Art. 26 – ICT risk management) fordern alle regelmäßige Sicherheitsüberprüfungen durch Experten." },
  { q: "Was unterscheidet einen Sicherheitsaudit von einem Penetrationstest?", a: "Ein Penetrationstest fokussiert auf technische Exploitation (manuell, PoC). Ein Sicherheitsaudit ist breiter: er umfasst technisches Testing + Policy-Prüfung + Compliance-Gap-Analyse + organisatorische Bewertung. Sodu Secure kombiniert beides in einem Audit." },
  { q: "Kann ich den Sicherheitsaudit für die ISO 27001-Zertifizierung verwenden?", a: "Ja – ein Sodu Secure Sicherheitsaudit-Bericht ist auf die Anforderungen akkreditierter ISO 27001-Zertifizierungsstellen ausgerichtet. Er adressiert direkt Annex A Controls und liefert den Nachweis für das Statement of Applicability (SoA)." },
];
