export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist ein IT Sicherheitsaudit?", a: "Ein IT Sicherheitsaudit (Sicherheitsaudit) ist eine umfassende Überprüfung der IT-Sicherheitslage eines Unternehmens - technisch und organisatorisch. Dabei werden Schwachstellen identifiziert, gegen Compliance-Anforderungen geprüft und mit priorisierten Maßnahmen versehen." },
  { q: "Was kostet ein Sicherheitsaudit?", a: "Ein automatisierter Schwachstellenscan ist ab 1.499 € buchbar. Ein manueller Sicherheitsaudit wird individuell auf Ihr Projekt zugeschnitten und nach Aufwand und Tagessätzen kalkuliert, meist zwischen 4.000 und 20.000 €. Den Ausschlag geben die Zahl der geprüften Systeme und ob organisatorische Punkte wie Richtlinien und Rollenkonzepte mitbewertet werden sollen." },
  { q: "Wie läuft ein Sicherheitsaudit ab?", a: "Ein Sicherheitsaudit läuft in vier Phasen ab: Kick-off mit Festlegung von Umfang und Zielen, Erhebung von Systemen, Prozessen und Richtlinien, technische Prüfung inklusive Schwachstellenanalyse und abschließend Bericht mit Gap-Analyse und Maßnahmenplan. Die Ergebnisse besprechen wir in einer Abschlusspräsentation mit IT und Geschäftsführung. Technische und organisatorische Befunde stehen dabei nebeneinander, damit Zuständigkeiten sofort erkennbar sind." },
  { q: "Wie lange dauert ein Sicherheitsaudit?", a: "Ein fokussierter IT Sicherheitsaudit dauert 2 bis 5 Tage. Ein vollständiger Unternehmens-Audit (technisch + Compliance + organisatorisch) 1 bis 2 Wochen. Bericht-Lieferung 48 Stunden nach Testabschluss." },
  { q: "Was gehört alles zu einem IT-Sicherheitsaudit?", a: "Zu einem IT-Sicherheitsaudit gehören technische und organisatorische Prüfungen: externe und interne Systeme, Webanwendungen, Cloud-Konfiguration, Active Directory und Backups auf der technischen Seite; Richtlinien, Rollen und Berechtigungen, Notfallplanung, Dienstleistersteuerung und Schulungsnachweise auf der organisatorischen. Erst beides zusammen zeigt, ob Ihre Sicherheitsmaßnahmen im Ernstfall tragen." },
  { q: "Wie kann ich prüfen, ob mein System sicher ist?", a: "Verlässlich beantworten lässt sich das nur anhand konkreter Prüffragen: Welche Ihrer Systeme sind aus dem Internet erreichbar, welche Software läuft in welcher Version, wo fehlen Updates, Härtung oder Mehrfaktor-Authentifizierung, und wer kommt an welche Daten? Ein Sicherheitsaudit beantwortet diese Fragen belegbar. Der Einstieg ist ein Schwachstellenscan ab 1.499 €, tiefer geht ein manueller Penetrationstest." },
  { q: "Für welche Compliance-Anforderungen brauche ich einen Sicherheitsaudit?", a: "NIS2 (Art. 21 - regelmäßige Risikomanagement-Maßnahmen), ISO 27001 (Annex A.8.8 technisches Schwachstellenmanagement), DSGVO Art. 32 (technische Sicherheitsmaßnahmen) und DORA (Art. 26 - Testen der digitalen operationalen Resilienz) fordern alle regelmäßige Sicherheitsüberprüfungen durch Experten." },
  { q: "Was unterscheidet einen Sicherheitsaudit von einem Penetrationstest?", a: "Ein Penetrationstest fokussiert auf technische Exploitation (manuell, PoC). Ein Sicherheitsaudit ist breiter: er umfasst technisches Testing + Policy-Prüfung + Compliance-Gap-Analyse + organisatorische Bewertung. Sodu Secure kombiniert beides in einem Audit." },
  { q: "Was benötigen Sie von uns für ein Sicherheitsaudit?", a: "Für den Start genügen eine Liste der zu prüfenden Systeme und Domains, ein Ansprechpartner aus der IT und die schriftliche Testfreigabe. Vorhandene Dokumente wie Richtlinien, Netzplan oder frühere Auditberichte beschleunigen die Arbeit, sind aber keine Voraussetzung. Für interne Prüfungen kommen ein VPN-Zugang oder ein Prüfgerät im Netz hinzu." },
  { q: "Wie werden unsere Daten während des Sicherheitsaudits geschützt?", a: "Vor Projektbeginn unterzeichnen wir ein NDA. Befunde und Nachweise werden verschlüsselt übertragen und ausschließlich von den eingesetzten Prüfern verarbeitet, personenbezogene Daten exportieren wir nicht. Nach Abschluss und Retest löschen wir die Projektdaten zur vereinbarten Frist. Auf Wunsch erhalten Sie einen Auftragsverarbeitungsvertrag nach DSGVO Art. 28." },
  { q: "Was passiert nach dem Sicherheitsaudit?", a: "Sie erhalten den Bericht in Deutsch und Englisch mit einer nach Risiko sortierten Maßnahmenliste und besprechen die Ergebnisse mit IT und Geschäftsführung. Danach setzen Sie die Maßnahmen um, bei Rückfragen sind wir erreichbar. Ist die Umsetzung abgeschlossen, läuft die Nachprüfung ohne Aufpreis und Sie bekommen die Behebung schriftlich bestätigt, etwa für Auditoren, Kunden oder Ihre Versicherung." },
  { q: "Kann ich den Sicherheitsaudit für die ISO 27001-Zertifizierung verwenden?", a: "Ja - ein Sodu Secure Sicherheitsaudit-Bericht ist auf die Anforderungen akkreditierter ISO 27001-Zertifizierungsstellen ausgerichtet. Er adressiert direkt Annex A Controls und liefert den Nachweis für das Statement of Applicability (SoA)." },
];
