export type FaqItem = { q: string; a: string };

export const FAQS: FaqItem[] = [
  { q: "Was ist ein Cyber Security Check?", a: "Ein Cyber Security Check ist eine systematische Überprüfung Ihrer IT-Infrastruktur auf Sicherheitslücken. Im Unterschied zum vollständigen Penetrationstest liegt der Fokus auf der Identifikation und Bewertung von Schwachstellen ohne vollständige Ausnutzung. Sie erhalten dadurch schnell einen belastbaren Überblick über Ihre Angriffsfläche und die dringendsten Risiken." },
  { q: "Was kostet ein Cyber Security Check?", a: "Ein automatisierter Schwachstellenscan als Einstieg startet bei Sodu Secure ab 1.499 €. Ein manuell durchgeführter Cyber Security Check wird nach Umfang kalkuliert und liegt meist zwischen 4.000 und 20.000 €, abhängig von Anzahl der Systeme, IP-Bereichen und Anwendungen. Wer zunächst nur wissen will, wie es um die von außen erreichbaren Systeme steht, beginnt mit dem Scan und entscheidet anhand der Fundlage über die weitere Prüftiefe." },
  { q: "Wie lange dauert ein Cyber Security Check?", a: "Je nach Scope dauert ein Check 1 bis 5 Werktage. Nach dem Scoping-Gespräch nennen wir Ihnen einen verbindlichen Zeitplan mit festem Start- und Endtermin. Den Bericht liefern wir innerhalb von 48 Stunden nach Testabschluss, kritische Findings melden wir sofort während der Prüfung." },
  { q: "Wie läuft ein Cyber Security Check ab?", a: "In vier Schritten: Scoping-Gespräch zur Festlegung der Systeme und Zugänge, Aufnahme der Angriffsfläche von außen und optional von innen, Prüfung und Bewertung der gefundenen Schwachstellen nach CVSS, anschließend Bericht und Ergebnisbesprechung. Die Prüfung erfolgt in einem mit Ihnen abgestimmten Zeitfenster, damit Ihr Betrieb planbar bleibt." },
  { q: "Was brauchen Sie von uns für den Cyber Security Check?", a: "In der Regel eine Liste der zu prüfenden Domains, IP-Bereiche und Anwendungen, eine schriftliche Testfreigabe des Systemverantwortlichen sowie bei authentifizierten Prüfungen Testzugänge. Bei internen Checks kommt ein VPN-Zugang hinzu. Mehr ist nicht nötig - alles Weitere klären wir im kostenlosen Scoping-Gespräch." },
  { q: "Stört der Cyber Security Check den laufenden Betrieb?", a: "Nein. Wir testen mit abgestimmter Intensität und in einem vereinbarten Zeitfenster, besonders lastintensive Prüfungen laufen auf Wunsch außerhalb der Geschäftszeiten oder auf einer Staging-Umgebung. Denial-of-Service-Tests sind standardmäßig ausgeschlossen. Während des Checks ist ein Ansprechpartner von uns erreichbar, falls Sie Auffälligkeiten sehen." },
  { q: "Für welche Unternehmen ist ein Cyber Security Check geeignet?", a: "Für alle Unternehmensgrößen: KMU, die erstmals ihren Sicherheitsstatus ermitteln wollen, bis hin zu größeren Organisationen, die bestehende Maßnahmen validieren möchten. Besonders sinnvoll ist der Check vor einem Pentest, vor einer ISO-27001-Zertifizierung, nach einer Migration oder wenn Kunden und Versicherungen einen Nachweis verlangen." },
  { q: "Wie kann ich prüfen, ob mein System sicher ist?", a: "Verlässlich nur, wenn jemand von außen tatsächlich versucht hineinzukommen. Ein Cyber Security Check erfasst Ihre von außen erreichbaren Systeme, gleicht eingesetzte Software gegen bekannte CVE-Schwachstellen ab, prüft Konfiguration, Verschlüsselung und Authentifizierung und bewertet die Funde nach Kritikalität. Interne Selbsteinschätzungen und Checklisten ersetzen diesen technischen Nachweis nicht." },
  { q: "Was ist der Unterschied zwischen Cyber Security Check und Pentest?", a: "Ein Cyber Security Check ist breiter und schneller und identifiziert Schwachstellen. Ein Penetrationstest geht tiefer und nutzt Schwachstellen aktiv aus, um die reale Auswirkung zu zeigen, etwa Datenzugriff oder Rechteausweitung. Viele Unternehmen beginnen mit einem Check und beauftragen anschließend einen Pentest für die kritischsten Systeme." },
  { q: "Erhalte ich ein Zertifikat oder einen Nachweis?", a: "Sie erhalten einen detaillierten Bericht in Deutsch und Englisch mit Management-Summary, allen Findings inklusive CVSS-Bewertung und priorisierten Maßnahmen. Auf Wunsch stellen wir zusätzlich ein Prüfzertifikat für interne oder externe Nachweispflichten aus, das Sie Kunden, Auditoren oder Ihrer Cyberversicherung vorlegen können." },
  { q: "Was passiert nach dem Cyber Security Check?", a: "Wir besprechen die Ergebnisse mit Ihrem Team und priorisieren gemeinsam die Behebung. Ihre IT arbeitet die Findings ab, für Rückfragen stehen wir bereit. Sind die kritischen Punkte geschlossen, bestätigen wir das in einer zweiten Prüfung ohne Zusatzkosten und halten den bereinigten Stand schriftlich für Ihren Nachweis fest." },
];
